/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-06-29 06:29:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1593176545452L));
    _jspx_dependants.put("jar:file:/C:/kyh/eclipse/webWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shobu/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1075171302000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1593409856501L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"content-script-type\" content=\"text/javascript\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>쇼부 Shobu</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("  <!--삭제필요 -->\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  \t.game{\r\n");
      out.write("\twidth:70%;\r\n");
      out.write("\tmargin: 20px auto 70px auto;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.teamlogo{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bold{\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tfont-size:medium;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.lab{\r\n");
      out.write("\t\tcolor: #9FA2A6;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.graph{\r\n");
      out.write("\t\twidth: 60%;\r\n");
      out.write("\t\tmargin: 0  auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* Bar Graph Horizontal */\r\n");
      out.write("\t.bar-graph{\r\n");
      out.write("\t  -webkit-animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  -moz-animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  opacity: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-horizontal {\r\n");
      out.write("\t  max-width: 90%;\r\n");
      out.write("\t  margin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-horizontal .bar-away{\r\n");
      out.write("\t  float: left;\r\n");
      out.write("\t  margin-bottom: 8px;\r\n");
      out.write("\t  width: 69.6%; /*변경*/\r\n");
      out.write("\t  display:contents;\r\n");
      out.write("\t}\r\n");
      out.write("\t.bar-graph-horizontal .bar-home{\r\n");
      out.write("\t  float: right;\r\n");
      out.write("\t  margin-bottom: 8px;\r\n");
      out.write("\t  width: 30.4%; /*변경*/\r\n");
      out.write("\t   display:contents;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-horizontal .bar-away .bar {\r\n");
      out.write("\t  border-radius: 3px;\r\n");
      out.write("\t  height: 55px;\r\n");
      out.write("\t  float: left;\r\n");
      out.write("\t  overflow: hidden;\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  width: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-horizontal .bar-home .bar {\r\n");
      out.write("\t  border-radius: 3px;\r\n");
      out.write("\t  height: 55px;\r\n");
      out.write("\t  float: right;\r\n");
      out.write("\t  overflow: hidden;\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  width: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-one .bar::after {\r\n");
      out.write("\t  -webkit-animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  -moz-animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  animation: fade-in-text 2.2s 0.1s forwards;\r\n");
      out.write("\t  color: #fff;\r\n");
      out.write("\t  content: attr(data-percentage);\r\n");
      out.write("\t  font-weight: 700;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  right: 16px;\r\n");
      out.write("\t  top: 17px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-one .bar-away .bar {\r\n");
      out.write("\t  -webkit-animation: show-bar-one 1.2s 0.1s forwards;\r\n");
      out.write("\t  -moz-animation: show-bar-one 1.2s 0.1s forwards;\r\n");
      out.write("\t  animation: show-bar-one 1.2s 0.1s forwards;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bar-graph-one .bar-home .bar {\r\n");
      out.write("\t  -webkit-animation: show-bar-two 1.2s 0.2s forwards;\r\n");
      out.write("\t  -moz-animation: show-bar-two 1.2s 0.2s forwards;\r\n");
      out.write("\t  animation: show-bar-two 1.2s 0.2s forwards;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* Bar Graph Horizontal Animations */\r\n");
      out.write("\t@-webkit-keyframes show-bar-one {\r\n");
      out.write("\t  0% {\r\n");
      out.write("\t    width: 0;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  100% {\r\n");
      out.write("\t    width: 69.6%; /*변경*/\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t@-webkit-keyframes show-bar-two {\r\n");
      out.write("\t  0% {\r\n");
      out.write("\t    width: 0;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  100% {\r\n");
      out.write("\t    width: 30.4%; /*변경*/\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t@-webkit-keyframes fade-in-text {\r\n");
      out.write("\t  0% {\r\n");
      out.write("\t    opacity: 0;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  100% {\r\n");
      out.write("\t    opacity: 1;\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\t/*~Graph*/\r\n");
      out.write("\t\r\n");
      out.write("\t/*carosel Control button shodow*/\r\n");
      out.write("\t.carousel-control {\r\n");
      out.write("\t    opacity: .1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*carosel dot*/\r\n");
      out.write("\t.carousel-indicators li {\r\n");
      out.write("\t    border: 1px solid #343D52;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.carousel-indicators .active {\r\n");
      out.write("\t    background-color: #343D52;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*Team Ranking Talbe*/\r\n");
      out.write("\t\r\n");
      out.write("\t.content-table {\r\n");
      out.write("\t  \t\tborder-collapse: collapse;\r\n");
      out.write("\t  \t\tmargin: 25px 0;\r\n");
      out.write("\t  \t\tfont-size: 0.9em;\r\n");
      out.write("\t  \t\tmin-width: 400px;\r\n");
      out.write("\t  \t\tborder-radius: 5px 5px 0 0;\r\n");
      out.write("\t  \t\toverflow: hidden;\r\n");
      out.write("\t  \t\tbox-shadow: 0 0 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table thead tr {\r\n");
      out.write("\t  \t\tbackground-color: #343d52;\r\n");
      out.write("\t  \t\tcolor: #FFFFFF;\r\n");
      out.write("\t  \t\ttext-align: left;\r\n");
      out.write("\t  \t\tfont-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table th,\r\n");
      out.write("\t\t.content-table td {\r\n");
      out.write("\t  \t\tpadding: 12px 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table tbody tr {\r\n");
      out.write("\t\t\tborder-bottom: 1px solid #DDDDDD;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table tbody tr:nth-of-type(even) {\r\n");
      out.write("\t\t\tbackground-color: #F3F3F3;\r\n");
      out.write("\t\t\tcolor: #343d52;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table tbody tr:nth-of-type(odd) {\r\n");
      out.write("\t\t\tbackground-color: #FFFFFF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.content-table tbody tr:last-of-type {\r\n");
      out.write("\t\t\tborder-bottom: 2px solid #009879;\r\n");
      out.write("\t\t}\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <script src=\"js/index.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \t\r\n");
      out.write(" \t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"content-script-type\" content=\"text/javascript\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>쇼부 Shobu</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("  .menu{\r\n");
      out.write("  \twidth: 25px;\r\n");
      out.write("  \tmargin: 20px 10px;\r\n");
      out.write("  }\r\n");
      out.write("  a:-webkit-any-link{\r\n");
      out.write("  \ttext-decoration:none;\r\n");
      out.write("  }\r\n");
      out.write("  #login{\r\n");
      out.write(" \twidth:100%;\r\n");
      out.write("  \tbackground-color: #343d52;\r\n");
      out.write("  \tcolor:#fff;\r\n");
      out.write("  \tposition:absolute; \r\n");
      out.write("  \tpadding: 3px 20px;\r\n");
      out.write("  \tbottom:0px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  </style>\r\n");
      out.write("    <script>\r\n");
      out.write("    // Open and close the sidebar on medium and small screens\r\n");
      out.write("    function navOpen() {\r\n");
      out.write("      document.getElementById(\"nav\").style.display = \"block\";\r\n");
      out.write("      document.getElementById(\"overlay\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("    function navClose() {\r\n");
      out.write("      document.getElementById(\"nav\").style.display = \"none\";\r\n");
      out.write("      document.getElementById(\"overlay\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- 슬라이드 메뉴바 -->\r\n");
      out.write("  <nav class=\"w3-sidebar w3-bar-block w3-collapse w3-animate-left w3-card\" style=\"z-index:3;width:250px;\" id=\"nav\">\r\n");
      out.write("    <div style=\"background-color: #343d52; height: 60px;\">토토</div>\r\n");
      out.write("    <a class=\"w3-bar-item w3-button w3-hide-large w3-large\" href=\"javascript:void(0)\" onclick=\"navClose()\">Close</a>\r\n");
      out.write("    <!-- 입력 -->\r\n");
      out.write("    <div id='menu' style=\"padding: 10px 20px;\">\r\n");
      out.write("\t    <a href=\"index.jsp\"><img class=\"menu\" src=\"image/menu/main.png\">메인</a><br>\r\n");
      out.write("\t    <a href=\"team.jsp\"><img class=\"menu\" src=\"image/menu/team.png\">팀정보</a><br>\r\n");
      out.write("\t    <a href=\"teampage.jsp\"><img class=\"menu\" src=\"image/menu/player.png\">선수정보</a><br>\r\n");
      out.write("\t    <a href=\"toto.do\"><img class=\"menu\" src=\"image/menu/toto.png\">모의토토</a><br>\r\n");
      out.write("\t    <a href=\"#\"><img class=\"menu\" src=\"image/menu/map.png\">토토 판매점</a><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"login\">\r\n");
      out.write("\t    <a href=\"../login.html\"><img class=\"menu\" src=\"image/menu/login.png\">로그인</a> \r\n");
      out.write("\t      \t<!-- <a href=\"logout.do\"><img class=\"menu\" src=\"image/menu/logout.png\">로그아웃</a> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("  </nav>\r\n");
      out.write("​\r\n");
      out.write("  <!-- 메뉴바 클릭 시 화면 어둡게 처리 -->\r\n");
      out.write("  <div class=\"w3-overlay w3-hide-large w3-animate-opacity\" onclick=\"navClose()\" style=\"cursor:pointer\" id=\"overlay\">\r\n");
      out.write("  </div>\r\n");
      out.write("​\r\n");
      out.write("  <!-- 상단 서치바, 유저정보(썸네일, 아이디) -->\r\n");
      out.write("  <div class=\"w3-main\" style=\"margin-left:250px;\">\r\n");
      out.write("    <header class=\"w3-container w3-top\" style=\"background-color: #343d52; color: white; height: 60px;\">\r\n");
      out.write("      <i class=\"fa fa-bars w3-button w3-hide-large w3-display-left\" onclick=\"navOpen()\"></i>\r\n");
      out.write("      <span class=\"w3-hide-large w3-right w3-animate-opacity\" style=\"position: relative; top: 25%;\">\r\n");
      out.write("      \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"40px\" height=\"40px\">\r\n");
      out.write("      </span>\r\n");
      out.write("      <span class=\"w3-hide-large w3-right w3-animate-opacity\" style=\"position: relative; top: 25%;\">\r\n");
      out.write("      \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님\r\n");
      out.write("      </span>\r\n");
      out.write("​\r\n");
      out.write("      <div class=\"w3-hide-small w3-hide-medium w3-animate-opacity\"\r\n");
      out.write("        style=\"width:100%; height: 100%; text-align: right; margin-left: -250px;\">\r\n");
      out.write("        <span style=\"position: relative; top: 25%;\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"40px\" height=\"40px\">\r\n");
      out.write("        </span>\r\n");
      out.write("        <span style=\"position: relative; top: 25%;\">\r\n");
      out.write("          ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님\r\n");
      out.write("        </span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("​\t\r\n");
      out.write("\t<!-- contents영역 -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("\t<section>\r\n");
      out.write("      <div class=\"card w3-card w3-container w3-padding-24\">\r\n");
      out.write("            <form>\r\n");
      out.write("                <img src=\"image/profile/default.png\" alt=\"\" width=\"100px\" height=\"100px\">\r\n");
      out.write("                <button class=\"w3-button w3-white w3-border w3-border-white w3-round-large\">Button</button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <label class=\"w3-text-blue\"><b>닉네임</b></label>\r\n");
      out.write("                <input class=\"w3-input w3-border\" type=\"text\">\r\n");
      out.write("                <label class=\"w3-text-blue\"><b>비밀번호</b></label>\r\n");
      out.write("                <input class=\"w3-input w3-border\" type=\"password\">\r\n");
      out.write("                <label class=\"w3-text-blue\"><b>비밀번호 확인</b></label>\r\n");
      out.write("                <input class=\"w3-input w3-border\" type=\"password\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <input class=\"w3-input\" type=\"submit\" value=\"변경\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("     </section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
